"""empty message

Revision ID: e8e004a8f94d
Revises: 
Create Date: 2016-11-16 23:26:55.199000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e004a8f94d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=66), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_curriculum_info',
    sa.Column('id_curriculum', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('tittle', sa.String(length=100), nullable=True),
    sa.Column('university', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=260), nullable=True),
    sa.Column('create_date_curriculum', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_curriculum')
    )
    op.create_table('user_personal_info',
    sa.Column('id_personal_user', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('country', sa.String(length=45), nullable=True),
    sa.Column('city', sa.String(length=45), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('repository', sa.String(length=120), nullable=True),
    sa.Column('social_red', sa.String(length=150), nullable=True),
    sa.Column('create_date_personal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_personal_user')
    )
    op.create_table('user_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('text_area', sa.UnicodeText(), nullable=True),
    sa.Column('upvote', sa.Integer(), nullable=True),
    sa.Column('downvote', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.Column('tag_one', sa.String(length=25), nullable=True),
    sa.Column('tag_two', sa.String(length=25), nullable=True),
    sa.Column('tag_three', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['id_question'], ['user_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answer_long',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=2000), nullable=True),
    sa.Column('answer_code', sa.UnicodeText(), nullable=True),
    sa.Column('upvote', sa.Integer(), nullable=True),
    sa.Column('downvote', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_question'], ['user_question.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answer_long')
    op.drop_table('tag_question')
    op.drop_table('user_question')
    op.drop_table('user_personal_info')
    op.drop_table('user_curriculum_info')
    op.drop_table('skills')
    op.drop_table('user')
    ### end Alembic commands ###
