USER_NESTED_FIELDS_EXCLUDES = [u'created',
                               u'updated',
                               u'information',
                               u'followed_count',
                               u'followers_count',
                               u'comments_count',
                               u'snippets_count',
                               u'questions_count',
                               u'answers_count',
                               u'stars_total_count',
                               u'upvotes_total_count',
                               u'downvotes_total_count']