"""empty message

Revision ID: 95f071691eec
Revises: dd614cf2eb0b
Create Date: 2016-12-05 15:58:44.219000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95f071691eec'
down_revision = 'dd614cf2eb0b'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_personal_info', 'city')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_personal_info', sa.Column('city', mysql.VARCHAR(length=45), nullable=True))
    ### end Alembic commands ###
