"""empty message

Revision ID: db34c50dc78d
Revises: fd5cf0d15302
Create Date: 2016-12-28 02:01:43.102000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db34c50dc78d'
down_revision = 'fd5cf0d15302'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_answer_star')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_answer_star',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_user'], [u'user.id'], name=u'users_answer_star_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
