"""empty message

Revision ID: dd614cf2eb0b
Revises: 1ae9dcf11ced
Create Date: 2016-11-27 16:57:22.768000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd614cf2eb0b'
down_revision = '1ae9dcf11ced'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_snippet', sa.Column('comment_text', sa.String(length=120), nullable=False))
    op.drop_column('comment_snippet', 'comment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_snippet', sa.Column('comment', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('comment_snippet', 'comment_text')
    ### end Alembic commands ###
